### ISSUE TITLE
By default outputs 6 tracks instead of 5

### ISSUE THREAD

**Issue by lenargasimov** [JeffreyCA/lastfm-recently-played-readme#14]
So I did this: added to the end  ```&count=4```

![Снимок экрана от 2022-04-13 20-20-10](https://user-images.githubusercontent.com/48679704/163235646-452556b5-7dc3-40d6-9d4f-28ad9540d663.png)

**Comment by JeffreyCA** [comment]
What browser/device are you using? Can you please share a screenshot?

This shows 5 tracks for me:
```
![](https://lastfm-recently-played.vercel.app/api?user=lenargasimov)
```

![](https://lastfm-recently-played.vercel.app/api?user=lenargasimov)

**Comment by lenargasimov** [comment]
MacBook Air 2011
Ubuntu 20.04.4 LTS
Google Chrome 100.0.4896.88

![Снимок экрана от 2022-04-14 09-46-22](https://user-images.githubusercontent.com/48679704/163329277-a0464c41-c6b4-4a27-8cbb-4bbec7977994.png)

**Comment by JeffreyCA** [comment]
Thanks, it should be fixed now (https://github.com/JeffreyCA/lastfm-recently-played-readme/commit/d50867ce11e9b2ce7b23deb8b2c53ebac1afa0c2).

**Comment by lenargasimov** [comment]
> Thanks, it should be fixed now (https://github.com/JeffreyCA/lastfm-recently-played-readme/commit/d50867ce11e9b2ce7b23deb8b2c53ebac1afa0c2).

Thank you for the opportunity to broadcast what I'm listening to👍🙂
