### ISSUE TITLE
"Preview" text overlaps "Scrobbling now" on mobile

### ISSUE THREAD

**Issue by BlueSlimee** [JeffreyCA/lastfm-recently-played-readme#3]
Hey! Your widget is awesome, but it looks weird on mobile devices.
The "Preview" text overlaps the "Scrobbling now" text, which doesn't look great at all.

![Screenshot_20210330-142612_Chrome](https://user-images.githubusercontent.com/33792776/113038460-8e97c400-9164-11eb-83e6-b2b437875d1d.jpg)

**Comment by JeffreyCA** [comment]
Thank you for catching this! I pushed out a fix (https://github.com/JeffreyCA/lastfm-recently-played-readme/commit/05dfc358ae1841e2d78114a0b13ac2e42e031f6a) which should take effect shortly.

**Comment by BlueSlimee** [comment]
It worked! Thank you for the quick answer.
