### ISSUE TITLE
Feature request: Show liked songs in the list

### ISSUE THREAD

**Issue by rollecode** [JeffreyCA/lastfm-recently-played-readme#6]
Hello! Thanks for the great embed. I was wondering is it possible to add liked song indicator to the list. I'm looking for a lightweight list of recently played so I can heart them in the app I'm currently using. As I'm using multiple apps (Pandora, PlexAmp, Spotify) the songs are not always matching the Last.fm database so this would come handy. I'd instantly see whether to rate or not.

**Comment by JeffreyCA** [comment]
Hi, thanks for the feature request! I'd like to get your thoughts on this initial version with the indicator:

```
https://lastfm-recently-played-1q3lra1bv-jeffreyca.vercel.app/api?user=JeffreyCA01&loves=true
```

![My scrobbles](https://lastfm-recently-played-1q3lra1bv-jeffreyca.vercel.app/api?user=JeffreyCA01&loves=true)

**Comment by rollecode** [comment]
@JeffreyCA Ooh, that's nice! Thanks for the fast response. I know this is the same approach than in Last.fm but they have them all in the same line. In this case it would be perhaps more aesthetically pleasing if the icon would be after the song title or just before the timestamp? Just an idea, but I'll accept whatever you decide. Thank you so much.

**Comment by JeffreyCA** [comment]
Done, see here: https://github.com/JeffreyCA/lastfm-recently-played-readme#show-loved-tracks

**Comment by rollecode** [comment]
Awesome! Thanks, I love it! Good work! 🎉
