### ISSUE TITLE
Feature request: Add auto update

### ISSUE THREAD

**Issue by rollecode** [JeffreyCA/lastfm-recently-played-readme#8]
Again, thanks for making this app, I love it. I'm using your app as actual app beside my PlexAmp player to be able to see which tracks are loved:

<img width="729" alt="Screen-Shot-2022-02-14-13-28-52 29" src="https://user-images.githubusercontent.com/1534150/153856398-4337c9e7-3178-461c-94a1-bbcde664d9a6.png">

I noticed the app won't update the status in real time. It could be as simple as periodical polling. Possible?

**Comment by JeffreyCA** [comment]
That's a cool application!

Since it generates a static SVG I don't think it's possible. You should be able to do the periodic refresh on the client side though.

**Comment by rollecode** [comment]
Right. Figured it out.

For future reference, if anyone wants to make a "Last.fm Recently Played Mac app" of this:

1. Add lastfm.css:

```css
svg { margin-top: 28px !important; }
```

2. Add lastfm.js:

```js
setTimeout(function() { window.location=window.location;}, 10000);
```

1. Create an app with [nativefier](https://github.com/nativefier/nativefier) (add your vercel app URL in place of mine):
```shell
nativefier -n "Last.fm" --hide-window-frame --title-bar-style "hidden" --max-height 415 --height 415 --max-width 400 --width 400 --inject lastfm.css --inject lastfm.js --background-color "#212121" "https://lastfm-recently-played-XXXXXXXXXX.vercel.app/api?user=rolle-&loved=true&loved_style=3"
```

3. Move to Applications

4. Create a icon with [iconsur](https://github.com/rikumi/iconsur):
```
sudo iconsur set /Applications/Last.fm.app/
```

5. Enjoy
